name = input("What is your name? ")
age = input("How old are you? ")
friend = input("What is your friend's name? ")
favorite_animal = input("What is your favorite animal? ")
print (f"Welcome to the adventure, {name}!")
print ()
print (f"When you were {age} years old, you and your friend {friend} went on an adventure together.")
print ()
print (f"You guys where searching for {favorite_animal} in the jungle and found it!")